FROM --platform=linux/amd64 alpine:3.19
RUN apk add --no-cache git make gcc musl-dev perl xz-dev mtools
WORKDIR /build
RUN git clone --depth 1 https://github.com/ipxe/ipxe.git
COPY embed.ipxe /build/ipxe/src/embed.ipxe
WORKDIR /build/ipxe/src
RUN make bin/undionly.kpxe EMBED=embed.ipxe
RUN make bin-x86_64-efi/ipxe.efi EMBED=embed.ipxe
RUN make bin-x86_64-efi/snponly.efi EMBED=embed.ipxe
